### ISSUE TITLE
Missing files/folders

### ISSUE THREAD

**Issue by ItsJasonPan** [yekeren/Story-Video_ads_understanding#1]
Great paper btw! I think some of the files/folders required to train/test a model is missing, namely protos/reader/utils and possibly more. Do you mind sharing those too? Thanks

**Comment by yekeren** [comment]
Sure, I have uploaded the source files under the protos/reader/utils directories, I have also uploaded the tools for extracting frame-level features. If you don't want to extract features from scratch, I have put the tfrecord files in a temporary directory (http://cs.pitt.edu/~yekeren/story.tar.gz, I shall remove them in a week). Please let me know if I still missed any required files.

**Comment by ItsJasonPan** [comment]
Awesome, thank you!
